name: Auto Redeploy Render App on Ping Failure

on:
  schedule:
    - cron: "*/5 * * * *" # हर 5 मिनट पर रन होगा
  workflow_dispatch:

jobs:
  check-and-redeploy:
    runs-on: ubuntu-latest

    steps:
      - name: Install jq (for JSON parsing)
        run: sudo apt-get update && sudo apt-get install -y jq

      - name: Ping Render App URL
        id: ping
        run: |
          echo "🔄 Pinging app..."
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" --max-time 10 https://n8n-ffmpeg-1-ysgq.onrender.com || echo "000")
          echo "HTTP Status: $STATUS"
          
          if [ "$STATUS" -ge 200 ] && [ "$STATUS" -lt 400 ]; then
            echo "✅ Ping successful"
            echo "redeploy_needed=false" >> $GITHUB_ENV
          else
            echo "⚠️ Ping failed or timeout"
            echo "redeploy_needed=true" >> $GITHUB_ENV
          fi

      - name: Check if Deploy is Already Running
        if: env.redeploy_needed == 'true'
        run: |
          echo "🔍 Checking last deploy status..."
          DEPLOY=$(curl -s -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys?limit=1)

          STATUS=$(echo "$DEPLOY" | jq -r '.[0].status')
          echo "Last deploy status: $STATUS"

          if [ "$STATUS" = "in_progress" ]; then
            echo "⏳ Another deploy is already running. Skipping redeploy."
            echo "redeploy_needed=false" >> $GITHUB_ENV
          fi

      - name: Trigger Redeploy if Down and No Deploy Running
        if: env.redeploy_needed == 'true'
        run: |
          echo "🚀 Triggering redeploy on Render..."
          RESPONSE=$(curl -s -X POST \
            -H "Accept: application/json" \
            -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys)

          echo "Redeploy Triggered. Response:"
          echo "$RESPONSE"
